version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: servcio_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - servcio_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: servcio_app
    ports:
      - "${APP_PORT}:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - servcio_network
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:
    driver: local

networks:
  servcio_network:
    driver: bridge